### ISSUE TITLE
'in' in braced arrow bodies in ForStatement inits is not parenthesized

### ISSUE THREAD

**Issue by lydell** [shapesecurity/shift-codegen-js#54]
test.js:

```js
const { parseModule } = require("shift-parser");
const { default: codeGen } = require("shift-codegen");

const input = "for (() => {(this in a)};;);";

const ast = parseModule(input);
const generated = codeGen(ast);

console.log(generated);

parseModule(generated);

console.log("done");
```

```
$ node test.js
for(()=>{this in a};;);
/home/lydell/test/node_modules/shift-parser/dist/parser.js:213
        throw this.createUnexpected(this.lookahead);
        ^

Error: [2:8]: Unexpected token "in"
    at new JsError (/home/lydell/test/node_modules/shift-parser/dist/tokenizer.js:165:81)
    at GenericParser.createError (/home/lydell/test/node_modules/shift-parser/dist/tokenizer.js:294:14)
    at GenericParser.createUnexpected (/home/lydell/test/node_modules/shift-parser/dist/tokenizer.js:269:23)
    at GenericParser.consumeSemicolon (/home/lydell/test/node_modules/shift-parser/dist/parser.js:213:20)
    at GenericParser.parseStatementHelper (/home/lydell/test/node_modules/shift-parser/dist/parser.js:636:20)
    at GenericParser.isolateCoverGrammar (/home/lydell/test/node_modules/shift-parser/dist/parser.js:1089:23)
    at GenericParser.parseStatement (/home/lydell/test/node_modules/shift-parser/dist/parser.js:578:23)
    at GenericParser.parseStatementListItem (/home/lydell/test/node_modules/shift-parser/dist/parser.js:570:25)
    at GenericParser.parseBody (/home/lydell/test/node_modules/shift-parser/dist/parser.js:306:61)
    at GenericParser.parseFunctionBody (/home/lydell/test/node_modules/shift-parser/dist/parser.js:281:44)
```

What happens here is that shift-codegen generates code that shift-parser cannot parse. This means that one of those has a bug.

When I tested on [astexplorer.net](http://astexplorer.net/), both shift-parser and esprima seem to reject `for (() => {this in false};;);`, while acorn, babylon, espree, flow, traceur and typescript allow it. I chose to trust shift-parser and esprima. Sorry if reporting in the wrong repo!

**Comment by michaelficarra** [comment]
This is a bug in the parser. The [`ConciseBody` grammar production](https://tc39.github.io/ecma262/#prod-ConciseBody) does not pass the `In` parameter to the `FunctionBody` in curlies.

**Comment by lydell** [comment]
Thanks for the explanation! I opened shapesecurity/shift-parser-js#349 instead.

**Comment by michaelficarra** [comment]
Too late! I've already opened https://github.com/shapesecurity/shift-parser-js/issues/348. 😛
