### ISSUE TITLE
Object literals with property keys containing spaces unsupported

### ISSUE THREAD

**Issue by sufianrhazi** [shapesecurity/shift-codegen-js#6]
Object literals with property keys that contain spaces in some cases fail to parse and in others fail to be generated.

I've added two test cases here: https://github.com/sufianrhazi/shift-codegen-js/commit/874f545b13ac701febe845249088973b9bc637c8

Those two test cases fail with the following errors:

```
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
 
  38 passing (558ms)
  2 failing
 
  1) Code generator generates simple ECMAScript ObjectExpression:
     [1:7]: Unexpected token :
  
 
  2) Code generator generates simple ECMAScript Assignment:
     ReferenceError: Utils is not defined
      at CodeGen.reducePropertyName (/home/srhazi/development/shift-codegen-js/lib/index.js:9:34707)
      at o.(anonymous function) [as PropertyName] (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:106:46)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:13:35
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:107:18
      at Array.map (native)
      at o.(anonymous function) [as DataProperty] (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:106:91)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:28:28
      at Array.map (native)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:27:19
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:107:18
      at Array.map (native)
      at o.(anonymous function) [as ObjectExpression] (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:106:91)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:13:35
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:107:18
      at Array.map (native)
      at o.(anonymous function) [as AssignmentExpression] (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:106:91)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:13:35
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:107:18
      at Array.map (native)
      at o.(anonymous function) [as ExpressionStatement] (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:106:91)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:28:28
      at Array.map (native)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:27:19
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:107:18
      at Array.map (native)
      at o.(anonymous function) [as FunctionBody] (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:106:91)
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:13:35
      at /home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:107:18
      at Array.map (native)
      at o.(anonymous function) [as Script] (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:106:91)
      at reduce (/home/srhazi/development/shift-codegen-js/node_modules/shift-reducer/lib/index.js:119:32)
      at codeGen (/home/srhazi/development/shift-codegen-js/lib/index.js:9:1116)
      at test (/home/srhazi/development/shift-codegen-js/test/simple.js:53:14)
      at Context.<anonymous> (/home/srhazi/development/shift-codegen-js/test/simple.js:117:7)
      at callFn (/home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runner.js:374:10)
      at /home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runner.js:452:12
      at next (/home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runner.js:299:14)
      at /home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runner.js:309:7
      at next (/home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runner.js:248:23)
      at Object._onImmediate (/home/srhazi/development/shift-codegen-js/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
 
 
 
 
=============================== Coverage summary ===============================
Statements   : 94.93% ( 393/414 )
Branches     : 91.55% ( 130/142 )
Functions    : 98.4% ( 123/125 )
Lines        : 94.93% ( 393/414 )
================================================================================
```

**Comment by michaelficarra** [comment]
Confirmed. Nice catch.
