### ISSUE TITLE
Shift reducer version out of sync

### ISSUE THREAD

**Issue by geelen** [shapesecurity/shift-codegen-js#84]
Installing `shift-codegen` installs version `6.0.0` (as expected) but that references `shift-reducer` `v5.0.0`. The `2019` branch lists `6.0.0` as the `shift-reducer` dependency but whatever's pushed to NPM hasn't been updated.

This matters for object spread syntax, and you can verify it's broken on https://shift-ast.org/codegen.html

![image](https://user-images.githubusercontent.com/23264/73845153-ef09ca80-4819-11ea-8588-63d7abf24f35.png)

**Comment by geelen** [comment]
Update: pinning the version to `6.0.0` doesn't work. The error message reads:

```
TypeError: reducer.reduceSpreadProperty is not a function
    at Object.SpreadProperty (~/src/projects/fab/node_modules/shift-reducer/dist/director.js:329:20)
    at ~/src/projects/fab/node_modules/shift-reducer/dist/director.js:304:31
    at Array.map (<anonymous>)
    at ObjectExpression (~/src/projects/fab/node_modules/shift-reducer/dist/director.js:303:79)
    at Object.AssignmentExpression (~/src/projects/fab/node_modules/shift-reducer/dist/director.js:50:150)
    at Object.ExpressionStatement (~/src/projects/fab/node_modules/shift-reducer/dist/director.js:185:92)
    at ~/src/projects/fab/node_modules/shift-reducer/dist/director.js:86:30
    at Array.map (<anonymous>)
    at Object.Block (~/src/projects/fab/node_modules/shift-reducer/dist/director.js:85:68)
    at Object.BlockStatement (~/src/projects/fab/node_modules/shift-reducer/dist/director.js:90:61)
```

**Comment by bakkot** [comment]
It's just that the ES2018 version of this project hadn't been successfully published, it looks like. shift-codegen 7.0.0 has just been published, and it should work.

**Comment by bakkot** [comment]
Going to close this as fixed; feel free to reopen if it not.
